server:
    port: 8080
    ip: localhost

spring:
  data:
    mongodb:
      # check port in mongodb
      uri: mongodb://localhost:27017/JoinMe

bootWithSwagger: false

# If it works on Linux, set it as /home/jay/JoinMe/uploadPic, D:/Source/IdeaProjects/JoinMe/uploadPic
uploadImagePath: /Users/jay/Pictures/uploadPic
